sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install: travis_retry pip install tox tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  skip_cleanup: true
  user: pmclanahan
  password:
    secure: XImyKrleMK5wSAom7c7zEQ74wp4Q0I5qT4xwfbWrmiiQeFP1p9YEcBmUXfAkJ01OOsPA5zuRzeVPKcBlyQVIwOigc6KijQOIkx6AY3aN6KCUKTbQnsiEda0/Gj0ZeAfv1tfuqQ1fZlU81Hr/lvq6Xw5N2NInJ1Cwkf0xUdKFORI=
  on:
    tags: true
    repo: pmclanahan/django-celery-email
